version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - echo  =======  Running Lint Tests ========
      - flake8 ./*py --statistics 
      - echo  =======  Running Code Tests ========
      - pytest 
        -s
        -v
        --cov 
        --cov-report=html:test-reports/coverage 
        --log-file=test-reports/logs.txt 
  post_build:
    commands:
      - ls -lR ./test-reports
      - echo Build completed on `date`
artifacts:
  files:
    - '**/**'
  base-directory: 'test-reports'

reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - "coverage/*"
      - "coverage/index.html"
    base-directory: 'test-reports'
    discard-paths: yes 
